FROM postgres

USER postgres
WORKDIR /app

COPY sql/create-schema.sql /docker-entrypoint-initdb.d/1_create.sql
COPY sql/insert-test-data.sql /docker-entrypoint-initdb.d/2_insert-test-data.sql

COPY --chown=postgres:postgres ./tests/scripts/wait-for-postgres.sh ./bin/wait-for-postgres.sh
RUN chmod +x ./bin/wait-for-postgres.sh

EXPOSE 5432
