name: Continuous Integration

on: [push]

jobs:
  build:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build with Gradle
        run: code/tic-tac-tow-service/gradlew -p code/tic-tac-tow-service ktlint